@Echo OFF
SET Services=HKEY_LOCAL_MACHINE\TK_SYSTEM\ControlSet001\Services
ECHO ============================================
reg delete %Services%\BTHUSB /f
reg delete %Services%\WwanSvc /f
reg delete %Services%\WdiServiceHost /f
reg delete %Services%\WdiSystemHost /f
reg delete %Services%\shpamsvc /f
reg delete %Services%\diagsvc /f
reg delete %Services%\swprv /f
reg delete %Services%\WFDSConMgrSvc /f
reg delete %Services%\pla /f
reg delete %Services%\WpnUserService /f
reg delete %Services%\WpnService /f
reg delete %Services%\BcastDVRUserService /f
reg delete %Services%\XblAuthManager /f
reg delete %Services%\XblGameSave /f
reg delete %Services%\XblNetApiSvc /f
reg delete %Services%\XboxNetApiSvc /f
reg delete %Services%\rasl2tp /f
reg delete %Services%\kdnic /f
reg delete %Services%\RasSstp /f
reg delete %Services%\BTAGService /f
reg delete %Services%\cbdhsvc /f
reg delete %Services%\ConsentUxUserSvc /f
reg delete %Services%\wbengine /f
reg delete %Services%\fhsvc /f
reg delete %Services%\DusmSvc /f
reg delete %Services%\InstallService /f
reg delete %Services%\SEMgrSvc /f
reg delete %Services%\TermService /f
reg delete %Services%\RasAuto /f
reg delete %Services%\RmSvc /f
reg delete %Services%\TapiSrv /f
reg delete %Services%\UdkUserSvc /f
reg delete %Services%\wcncsvc /f
reg delete %Services%\stisvc /f
reg delete %Services%\wisvc /f
reg delete %Services%\upnphost /f
reg delete %Services%\icssvc /f
reg delete %Services%\WSearch /f
reg delete %Services%\BluetoothUserService /f
reg delete %Services%\PcaSvc /f
reg delete %Services%\PeerDistSvc /f
reg delete %Services%\PhoneSvc /f
reg delete %Services%\PimIndexMaintenanceSvc /f
reg delete %Services%\PNRPAutoReg /f
reg delete %Services%\p2pimsvc /f
reg delete %Services%\p2psvc /f
reg delete %Services%\BthA2dp /f
reg delete %Services%\LanmanServer /f
reg delete %Services%\Microsoft_Bluetooth_AvrcpTransport /f
reg delete %Services%\MessagingService /f
reg delete %Services%\lmhosts /f
reg delete %Services%\LanmanWorkstation /f
reg delete %Services%\BthAvctpSvc /f
reg delete %Services%\BthEnum /f
reg delete %Services%\FrameServer /f
reg delete %Services%\diagnosticshub.standardcollector.service /f
reg delete %Services%\DiagTrack /f
reg delete %Services%\dmwappushservice /f
reg delete %Services%\CscService /f
reg delete %Services%\BTHMODEM /f
reg delete %Services%\bthserv /f
reg delete %Services%\BthMini /f
reg delete %Services%\BthLEEnum /f
reg delete %Services%\CDPUserSvc /f
reg delete %Services%\CDPSvc /f
reg delete %Services%\CaptureService /f
reg delete %Services%\PNRPsvc /f
reg delete %Services%\AarSvc /f
reg delete %Services%\AJRouter /f
reg delete %Services%\autotimesvc /f
reg delete %Services%\PptpMiniport /f
reg delete %Services%\PushToInstall /f
reg delete %Services%\QWAVE /f
reg delete %Services%\QWAVEdrv /f
reg delete %Services%\RasPppoe /f
reg delete %Services%\RasMan /f
reg delete %Services%\RasAgileVpn /f
reg delete %Services%\RemoteRegistry /f
reg delete %Services%\RemoteAccess /f
reg delete %Services%\SensorDataService /f
reg delete %Services%\SensorService /f
reg delete %Services%\SensrSvc /f
reg delete %Services%\SessionEnv /f
reg delete %Services%\SmsRouter /f
reg delete %Services%\SSDPSRV /f
reg delete %Services%\TabletInputService /f
reg delete %Services%\Telemetry /f
reg delete %Services%\UmRdpService /f
reg delete %Services%\UserDataSvc /f
reg delete %Services%\UnistoreSvc /f
reg delete %Services%\WarpJITsvc /f
reg delete %Services%\WiaRpc /f
reg delete %Services%\WinRM /f
reg delete %Services%\wercplsupport /f
reg delete %Services%\WebClient /f
reg delete %Services%\WalletService /f
reg delete %Services%\xboxgip /f
reg delete %Services%\XboxGipSvc /f
reg delete %Services%\NdisWan /f
reg delete %Services%\ndiswanlegacy /f
reg delete %Services%\BTHPORT /f
reg delete %Services%\IKEEXT /f
reg delete %Services%\KtmRm /f
reg delete %Services%\LxpSvc /f
reg delete %Services%\WerSvc /f
reg delete %Services%\VSS /f
reg delete %Services%\DevQueryBroker /f
reg delete %Services%\TroubleShootingSvc /f
reg delete %Services%\BthHFEnum /f
reg delete %Services%\captureservice /f
pause